# Generated by Django 2.1.7 on 2020-02-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigationrecord', '0002_navigation_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigationrecord.Vehicle'),
        ),
    ]
